// Auto-generated by cbindgen — do not edit by hand.

#ifndef MONITOR_RS_H
#define MONITOR_RS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

#if defined(__APPLE__)
#define MRS_MAX_CORES 64
#endif

#if defined(__APPLE__)
#define MRS_MAX_PROCS 16
#endif

#if defined(__APPLE__)
#define MRS_PROC_NAME 64
#endif

#if defined(__APPLE__)
typedef struct MrsHandle MrsHandle;
#endif

#if defined(__APPLE__)
typedef struct {
  uint32_t pid;
  char name[MRS_PROC_NAME];
  float cpu_pct;
  uint64_t rss_bytes;
} MrsProcInfo;
#endif

#if defined(__APPLE__)
typedef struct {
  double ts_seconds;
  float cpu_total_pct;
  uint8_t core_count;
  float cpu_per_core_pct[MRS_MAX_CORES];
  int8_t gpu_present;
  float gpu_pct;
  uint64_t mem_used_bytes;
  uint64_t mem_total_bytes;
  uint8_t mem_pressure;
  uint64_t swap_used_bytes;
  uint64_t swap_total_bytes;
  uint8_t proc_count;
  MrsProcInfo procs[MRS_MAX_PROCS];
  uint64_t net_rx_bps;
  uint64_t net_tx_bps;
  uint64_t disk_read_bps;
  uint64_t disk_write_bps;
  uint8_t battery_present;
  uint8_t battery_charging;
  float battery_pct;
  uint8_t cpu_temp_present;
  float cpu_temp_c;
  uint8_t gpu_temp_present;
  float gpu_temp_c;
  uint8_t proc_count_by_mem;
  MrsProcInfo procs_by_mem[MRS_MAX_PROCS];
} MrsSample;
#endif

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#if defined(__APPLE__)
MrsHandle *monitor_rs_start(void);
#endif

#if defined(__APPLE__)
/**
 * # Safety
 * `h` must be a non-null pointer previously returned by `monitor_rs_start` and
 * not yet freed. After this call the pointer is invalid.
 */
void monitor_rs_stop(MrsHandle *h);
#endif

#if defined(__APPLE__)
/**
 * # Safety
 * `h` must be a valid handle returned by `monitor_rs_start` and not yet freed.
 * `out` must point to a writable `MrsSample`-sized allocation.
 */
int monitor_rs_latest(MrsHandle *h, MrsSample *out);
#endif

#if defined(__APPLE__)
/**
 * # Safety
 * `h` must be a valid handle returned by `monitor_rs_start` and not yet freed.
 * `out` must point to a writable array of at least `n` `MrsSample` elements.
 */
uintptr_t monitor_rs_recent(MrsHandle *h, uintptr_t n, MrsSample *out);
#endif

#if defined(__APPLE__)
/**
 * # Safety
 * `h` must be a valid handle returned by `monitor_rs_start` and not yet freed.
 * The returned pointer must be freed with `monitor_rs_string_free`.
 */
const char *monitor_rs_settings_get(MrsHandle *h);
#endif

#if defined(__APPLE__)
/**
 * # Safety
 * `h` must be a valid handle returned by `monitor_rs_start` and not yet freed
 * (may be null, in which case settings are saved but not reflected in the handle).
 * `json` must be a valid NUL-terminated UTF-8 string.
 */
int monitor_rs_settings_set(MrsHandle *h, const char *json);
#endif

#if defined(__APPLE__)
/**
 * Tell the sampler whether the popover is currently visible. When inactive,
 * the sampler skips the expensive `sysinfo` process refresh and reuses the
 * last-computed top-process lists. Pass non-zero for active, zero for
 * inactive. Safe to call from any thread.
 *
 * # Safety
 * `h` must be a valid handle returned by `monitor_rs_start` and not yet freed.
 */
void monitor_rs_set_active(MrsHandle *h, uint8_t active);
#endif

#if defined(__APPLE__)
/**
 * # Safety
 * `s` must be a pointer previously returned by `monitor_rs_settings_get`, or null.
 * After this call the pointer is invalid.
 */
void monitor_rs_string_free(const char *s);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MONITOR_RS_H */
