// Auto-generated by cbindgen — do not edit by hand.

#ifndef MONITOR_RS_H
#define MONITOR_RS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

#if defined(__APPLE__)
#define MRS_MAX_CORES 64
#endif

#if defined(__APPLE__)
#define MRS_MAX_PROCS 16
#endif

#if defined(__APPLE__)
#define MRS_PROC_NAME 64
#endif

#if defined(__APPLE__)
typedef struct MrsHandle MrsHandle;
#endif

#if defined(__APPLE__)
typedef struct {
  uint32_t pid;
  char name[MRS_PROC_NAME];
  float cpu_pct;
  uint64_t rss_bytes;
} MrsProcInfo;
#endif

#if defined(__APPLE__)
typedef struct {
  double ts_seconds;
  float cpu_total_pct;
  uint8_t core_count;
  float cpu_per_core_pct[MRS_MAX_CORES];
  int8_t gpu_present;
  float gpu_pct;
  uint64_t mem_used_bytes;
  uint64_t mem_total_bytes;
  uint8_t mem_pressure;
  uint64_t swap_used_bytes;
  uint64_t swap_total_bytes;
  uint8_t proc_count;
  MrsProcInfo procs[MRS_MAX_PROCS];
} MrsSample;
#endif

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#if defined(__APPLE__)
MrsHandle *monitor_rs_start(void);
#endif

#if defined(__APPLE__)
void monitor_rs_stop(MrsHandle *h);
#endif

#if defined(__APPLE__)
int monitor_rs_latest(MrsHandle *h, MrsSample *out);
#endif

#if defined(__APPLE__)
uintptr_t monitor_rs_recent(MrsHandle *h, uintptr_t n, MrsSample *out);
#endif

#if defined(__APPLE__)
const char *monitor_rs_settings_get(MrsHandle *h);
#endif

#if defined(__APPLE__)
int monitor_rs_settings_set(MrsHandle *h, const char *json);
#endif

#if defined(__APPLE__)
void monitor_rs_string_free(const char *s);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MONITOR_RS_H */
